"""add registration cancellations

Revision ID: 1f64ab674c8e
Revises: 716e5027b174
Create Date: 2026-09-15 10:47:38.812019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f64ab674c8e'
down_revision: Union[str, Sequence[str], None] = '716e5027b174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('event_status', sa.String(length=32), nullable=False),
    sa.Column('after_deadline', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.String(length=32), nullable=True),
    sa.Column('decision_note', sa.String(length=1000), nullable=True),
    sa.Column('penalty_applied', sa.Boolean(), nullable=False),
    sa.Column('penalty_note', sa.String(length=512), nullable=True),
    sa.Column('released_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('self', 'request', 'admin')", name=op.f('ck_registration_cancellations_mode_valid')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'withdrawn')", name=op.f('ck_registration_cancellations_status_valid')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_registration_cancellations_decided_by_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_registration_cancellations_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_registration_cancellations_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_registration_cancellations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_cancellations'))
    )
    with op.batch_alter_table('registration_cancellations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_cancellations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_cancellations_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_cancellations_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_cancellations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_cancellations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_registration_cancellations_pending', ['registration_id'], unique=True, sqlite_where=sa.text("status = 'pending'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_cancellations', schema=None) as batch_op:
        batch_op.drop_index('uq_registration_cancellations_pending', sqlite_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_registration_cancellations_user_id'))
        batch_op.drop_index(batch_op.f('ix_registration_cancellations_status'))
        batch_op.drop_index(batch_op.f('ix_registration_cancellations_requested_at'))
        batch_op.drop_index(batch_op.f('ix_registration_cancellations_registration_id'))
        batch_op.drop_index(batch_op.f('ix_registration_cancellations_event_id'))

    op.drop_table('registration_cancellations')
    # ### end Alembic commands ###
