"""initial schema

Revision ID: f52c2f1cd288
Revises: 
Create Date: 2026-09-11 21:35:33.745761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52c2f1cd288'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registration_opens_at', sa.String(length=32), nullable=True),
    sa.Column('registration_closes_at', sa.String(length=32), nullable=True),
    sa.Column('terms_version', sa.String(length=16), nullable=False),
    sa.Column('terms_content', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'registration_open', 'registration_closed', 'allocation_processing', 'information_published', 'event_started', 'completed')", name=op.f('ck_events_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('code', name=op.f('uq_events_code'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('work_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('airport_code', sa.String(length=8), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_locations')),
    sa.UniqueConstraint('code', name=op.f('uq_work_locations_code'))
    )
    op.create_table('event_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_settings_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_settings')),
    sa.UniqueConstraint('event_id', 'key', name='uq_event_settings_event_key')
    )
    op.create_table('gala_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.String(length=32), nullable=True),
    sa.Column('stage_position', sa.String(length=16), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=False),
    sa.Column('grid_height', sa.Integer(), nullable=False),
    sa.Column('selection_status', sa.String(length=16), nullable=False),
    sa.Column('turn_seconds', sa.Integer(), nullable=False),
    sa.Column('hold_seconds', sa.Integer(), nullable=False),
    sa.Column('draw_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("selection_status IN ('closed', 'drawing', 'open', 'finalized')", name=op.f('ck_gala_layouts_selection_status_valid')),
    sa.CheckConstraint('hold_seconds > 0', name=op.f('ck_gala_layouts_hold_seconds_positive')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_gala_layouts_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gala_layouts'))
    )
    with op.batch_alter_table('gala_layouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gala_layouts_event_id'), ['event_id'], unique=False)

    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('check_in_at', sa.String(length=32), nullable=True),
    sa.Column('check_out_at', sa.String(length=32), nullable=True),
    sa.Column('map_url', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_hotels_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotels'))
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_event_id'), ['event_id'], unique=False)

    op.create_table('itinerary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('audience', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_itinerary_items_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_items'))
    )
    with op.batch_alter_table('itinerary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_items_day_date'), ['day_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_items_event_id'), ['event_id'], unique=False)

    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("doc_type IN ('terms', 'faq', 'guide', 'itinerary')", name=op.f('ck_policy_documents_doc_type_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_policy_documents_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_documents'))
    )
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_documents_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_documents_is_indexed'), ['is_indexed'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('earliest_departure', sa.String(length=5), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_shifts_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('event_id', 'code', name='uq_shifts_event_code')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_event_id'), ['event_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('leader_user_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_teams_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('code', name=op.f('uq_teams_code'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_leader_user_id'), ['leader_user_id'], unique=False)

    op.create_table('trip_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('leg_date', sa.String(length=10), nullable=True),
    sa.Column('is_airport_linked', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("direction IN ('outbound', 'return')", name=op.f('ck_trip_legs_direction_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_trip_legs_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_legs')),
    sa.UniqueConstraint('event_id', 'code', name='uq_trip_legs_event_code')
    )
    with op.batch_alter_table('trip_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_legs_event_id'), ['event_id'], unique=False)

    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('flight_code', sa.String(length=16), nullable=False),
    sa.Column('airline', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('departure_airport', sa.String(length=8), nullable=False),
    sa.Column('arrival_airport', sa.String(length=8), nullable=False),
    sa.Column('departure_time', sa.String(length=32), nullable=False),
    sa.Column('arrival_time', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('reserved_slots', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('outbound', 'return')", name=op.f('ck_flights_direction_valid')),
    sa.CheckConstraint('capacity >= 0', name=op.f('ck_flights_capacity_non_negative')),
    sa.CheckConstraint('reserved_slots <= capacity', name=op.f('ck_flights_reserved_within_capacity')),
    sa.CheckConstraint('reserved_slots >= 0', name=op.f('ck_flights_reserved_non_negative')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_flights_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_flights_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flights')),
    sa.UniqueConstraint('event_id', 'flight_code', 'direction', 'departure_time', name='uq_flights_event_code_direction_time')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flights_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_flights_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flights_shift_id'), ['shift_id'], unique=False)

    op.create_table('gala_draw_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('draw_position', sa.Integer(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('turn_started_at', sa.String(length=32), nullable=True),
    sa.Column('turn_ends_at', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'active', 'done', 'skipped')", name=op.f('ck_gala_draw_orders_status_valid')),
    sa.CheckConstraint('quota >= 0', name=op.f('ck_gala_draw_orders_quota_non_negative')),
    sa.ForeignKeyConstraint(['layout_id'], ['gala_layouts.id'], name=op.f('fk_gala_draw_orders_layout_id_gala_layouts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_gala_draw_orders_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gala_draw_orders')),
    sa.UniqueConstraint('layout_id', 'draw_position', name='uq_gala_draw_layout_position'),
    sa.UniqueConstraint('layout_id', 'team_id', name='uq_gala_draw_layout_team')
    )
    with op.batch_alter_table('gala_draw_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gala_draw_orders_layout_id'), ['layout_id'], unique=False)

    op.create_table('gala_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('table_code', sa.String(length=16), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('seat_count > 0', name=op.f('ck_gala_tables_seat_count_positive')),
    sa.ForeignKeyConstraint(['layout_id'], ['gala_layouts.id'], name=op.f('fk_gala_tables_layout_id_gala_layouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gala_tables')),
    sa.UniqueConstraint('layout_id', 'table_code', name='uq_gala_tables_layout_code')
    )
    with op.batch_alter_table('gala_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gala_tables_layout_id'), ['layout_id'], unique=False)

    op.create_table('pickup_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('trip_leg_id', sa.Integer(), nullable=True),
    sa.Column('work_location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('map_url', sa.String(length=512), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_pickup_points_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_leg_id'], ['trip_legs.id'], name=op.f('fk_pickup_points_trip_leg_id_trip_legs')),
    sa.ForeignKeyConstraint(['work_location_id'], ['work_locations.id'], name=op.f('fk_pickup_points_work_location_id_work_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_points'))
    )
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_points_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_points_trip_leg_id'), ['trip_leg_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('floor', sa.String(length=16), nullable=True),
    sa.Column('gender_policy', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.CheckConstraint("gender_policy IN ('any', 'male', 'female')", name=op.f('ck_rooms_gender_policy_valid')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_rooms_capacity_positive')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_rooms_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('hotel_id', 'room_number', name='uq_rooms_hotel_number')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_hotel_id'), ['hotel_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('work_location_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('join_date', sa.String(length=10), nullable=True),
    sa.Column('id_card_number', sa.String(length=32), nullable=True),
    sa.Column('id_card_type', sa.String(length=16), nullable=True),
    sa.Column('id_card_issue_date', sa.String(length=10), nullable=True),
    sa.Column('id_card_issue_place', sa.String(length=255), nullable=True),
    sa.Column('shirt_size', sa.String(length=8), nullable=True),
    sa.Column('dietary_restriction', sa.String(length=255), nullable=True),
    sa.Column('health_note', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male', 'female', 'other')", name=op.f('ck_users_gender_valid')),
    sa.CheckConstraint("role IN ('employee', 'team_leader', 'admin', 'super_admin')", name=op.f('ck_users_role_valid')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_users_team_id_teams')),
    sa.ForeignKeyConstraint(['work_location_id'], ['work_locations.id'], name=op.f('fk_users_work_location_id_work_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('sso_subject', name=op.f('uq_users_sso_subject'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.String(length=32), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'urgent')", name=op.f('ck_announcements_severity_valid')),
    sa.CheckConstraint("target_type IN ('all', 'team', 'flight', 'bus', 'user')", name=op.f('ck_announcements_target_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_announcements_created_by_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_announcements_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_published_at'), ['published_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_audit_logs_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_time', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_id'), ['event_id'], unique=False)

    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('trip_leg_id', sa.Integer(), nullable=False),
    sa.Column('bus_code', sa.String(length=32), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.Column('dropoff_point', sa.String(length=255), nullable=True),
    sa.Column('gather_time', sa.String(length=32), nullable=True),
    sa.Column('departure_time', sa.String(length=32), nullable=True),
    sa.Column('leader_user_id', sa.Integer(), nullable=True),
    sa.Column('leader_name', sa.String(length=255), nullable=True),
    sa.Column('leader_phone', sa.String(length=32), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=32), nullable=True),
    sa.Column('linked_flight_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_buses_capacity_positive')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_buses_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], name=op.f('fk_buses_leader_user_id_users')),
    sa.ForeignKeyConstraint(['linked_flight_id'], ['flights.id'], name=op.f('fk_buses_linked_flight_id_flights')),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], name=op.f('fk_buses_pickup_point_id_pickup_points')),
    sa.ForeignKeyConstraint(['trip_leg_id'], ['trip_legs.id'], name=op.f('fk_buses_trip_leg_id_trip_legs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buses')),
    sa.UniqueConstraint('event_id', 'trip_leg_id', 'bus_code', name='uq_buses_event_leg_code')
    )
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buses_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buses_linked_flight_id'), ['linked_flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buses_trip_leg_id'), ['trip_leg_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_chat_sessions_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('terms_version', sa.String(length=16), nullable=False),
    sa.Column('agreed_at', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_consents_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('user_id', 'event_id', 'terms_version', name='uq_consents_user_event_version')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.String(length=64), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed')", name=op.f('ck_email_logs_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_user_id'), ['user_id'], unique=False)

    op.create_table('gala_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['gala_tables.id'], name=op.f('fk_gala_seats_table_id_gala_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gala_seats')),
    sa.UniqueConstraint('table_id', 'seat_number', name='uq_gala_seats_table_number')
    )
    with op.batch_alter_table('gala_seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gala_seats_table_id'), ['table_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_participating', sa.Boolean(), nullable=False),
    sa.Column('not_participating_reason', sa.String(length=512), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('is_shift_locked', sa.Boolean(), nullable=False),
    sa.Column('departure_location_id', sa.Integer(), nullable=True),
    sa.Column('wish_note', sa.Text(), nullable=True),
    sa.Column('companion_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.String(length=32), nullable=True),
    sa.Column('cancelled_at', sa.String(length=32), nullable=True),
    sa.Column('cancel_reason', sa.String(length=512), nullable=True),
    sa.Column('penalty_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'cancelled')", name=op.f('ck_registrations_status_valid')),
    sa.CheckConstraint('companion_count >= 0', name=op.f('ck_registrations_companion_non_negative')),
    sa.ForeignKeyConstraint(['departure_location_id'], ['work_locations.id'], name=op.f('fk_registrations_departure_location_id_work_locations')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_registrations_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_registrations_shift_id_shifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_registrations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrations')),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_registrations_event_user')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_user_id'), ['user_id'], unique=False)

    op.create_table('bus_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('trip_leg_id', sa.Integer(), nullable=False),
    sa.Column('assignment_mode', sa.String(length=16), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("assignment_mode IN ('auto', 'manual')", name=op.f('ck_bus_assignments_mode_valid')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_bus_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_bus_assignments_bus_id_buses')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_bus_assignments_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_leg_id'], ['trip_legs.id'], name=op.f('fk_bus_assignments_trip_leg_id_trip_legs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bus_assignments')),
    sa.UniqueConstraint('registration_id', 'trip_leg_id', name='uq_bus_assignments_registration_leg')
    )
    with op.batch_alter_table('bus_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_assignments_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_assignments_registration_id'), ['registration_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_role_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('flight_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('seat_number', sa.String(length=8), nullable=True),
    sa.Column('ticket_code', sa.String(length=32), nullable=True),
    sa.Column('assignment_mode', sa.String(length=16), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("assignment_mode IN ('auto', 'manual')", name=op.f('ck_flight_assignments_mode_valid')),
    sa.CheckConstraint("direction IN ('outbound', 'return')", name=op.f('ck_flight_assignments_direction_valid')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_flight_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('fk_flight_assignments_flight_id_flights')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_flight_assignments_registration_id_registrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_assignments')),
    sa.UniqueConstraint('registration_id', 'direction', name='uq_flight_assignments_registration_direction')
    )
    with op.batch_alter_table('flight_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_assignments_flight_id'), ['flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_assignments_registration_id'), ['registration_id'], unique=False)

    op.create_table('gala_seat_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_gala_seat_assignments_confirmed_by_users')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_gala_seat_assignments_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['gala_seats.id'], name=op.f('fk_gala_seat_assignments_seat_id_gala_seats')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_gala_seat_assignments_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gala_seat_assignments')),
    sa.UniqueConstraint('registration_id', name='uq_gala_seat_assignments_registration'),
    sa.UniqueConstraint('seat_id', name='uq_gala_seat_assignments_seat')
    )
    with op.batch_alter_table('gala_seat_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gala_seat_assignments_team_id'), ['team_id'], unique=False)

    op.create_table('gala_seat_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('held_by', sa.Integer(), nullable=False),
    sa.Column('held_at', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['held_by'], ['users.id'], name=op.f('fk_gala_seat_holds_held_by_users')),
    sa.ForeignKeyConstraint(['seat_id'], ['gala_seats.id'], name=op.f('fk_gala_seat_holds_seat_id_gala_seats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_gala_seat_holds_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gala_seat_holds')),
    sa.UniqueConstraint('seat_id', name='uq_gala_seat_holds_seat')
    )
    with op.batch_alter_table('gala_seat_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gala_seat_holds_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gala_seat_holds_team_id'), ['team_id'], unique=False)

    op.create_table('registration_bus_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('trip_leg_id', sa.Integer(), nullable=False),
    sa.Column('needs_bus', sa.Boolean(), nullable=False),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], name=op.f('fk_registration_bus_needs_pickup_point_id_pickup_points')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_registration_bus_needs_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_leg_id'], ['trip_legs.id'], name=op.f('fk_registration_bus_needs_trip_leg_id_trip_legs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_bus_needs')),
    sa.UniqueConstraint('registration_id', 'trip_leg_id', name='uq_bus_needs_registration_leg')
    )
    with op.batch_alter_table('registration_bus_needs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_bus_needs_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_bus_needs_trip_leg_id'), ['trip_leg_id'], unique=False)

    op.create_table('room_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_room_captain', sa.Boolean(), nullable=False),
    sa.Column('assignment_mode', sa.String(length=16), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.CheckConstraint("assignment_mode IN ('auto', 'manual')", name=op.f('ck_room_assignments_mode_valid')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_room_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_room_assignments_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_assignments_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_assignments')),
    sa.UniqueConstraint('registration_id', name='uq_room_assignments_registration')
    )
    with op.batch_alter_table('room_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_assignments_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_assignments_room_id'))

    op.drop_table('room_assignments')
    with op.batch_alter_table('registration_bus_needs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_bus_needs_trip_leg_id'))
        batch_op.drop_index(batch_op.f('ix_registration_bus_needs_registration_id'))

    op.drop_table('registration_bus_needs')
    with op.batch_alter_table('gala_seat_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gala_seat_holds_team_id'))
        batch_op.drop_index(batch_op.f('ix_gala_seat_holds_expires_at'))

    op.drop_table('gala_seat_holds')
    with op.batch_alter_table('gala_seat_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gala_seat_assignments_team_id'))

    op.drop_table('gala_seat_assignments')
    with op.batch_alter_table('flight_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_assignments_registration_id'))
        batch_op.drop_index(batch_op.f('ix_flight_assignments_flight_id'))

    op.drop_table('flight_assignments')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('bus_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_assignments_registration_id'))
        batch_op.drop_index(batch_op.f('ix_bus_assignments_bus_id'))

    op.drop_table('bus_assignments')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_shift_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_event_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('gala_seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gala_seats_table_id'))

    op.drop_table('gala_seats')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_logs_template'))
        batch_op.drop_index(batch_op.f('ix_email_logs_status'))

    op.drop_table('email_logs')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_consents_event_id'))

    op.drop_table('consents')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buses_trip_leg_id'))
        batch_op.drop_index(batch_op.f('ix_buses_linked_flight_id'))
        batch_op.drop_index(batch_op.f('ix_buses_event_id'))

    op.drop_table('buses')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_id'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_actor_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_published_at'))
        batch_op.drop_index(batch_op.f('ix_announcements_event_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_team_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_employee_code'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_hotel_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_points_trip_leg_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_points_event_id'))

    op.drop_table('pickup_points')
    with op.batch_alter_table('gala_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gala_tables_layout_id'))

    op.drop_table('gala_tables')
    with op.batch_alter_table('gala_draw_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gala_draw_orders_layout_id'))

    op.drop_table('gala_draw_orders')
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flights_shift_id'))
        batch_op.drop_index(batch_op.f('ix_flights_event_id'))
        batch_op.drop_index(batch_op.f('ix_flights_direction'))

    op.drop_table('flights')
    with op.batch_alter_table('trip_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_legs_event_id'))

    op.drop_table('trip_legs')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_leader_user_id'))

    op.drop_table('teams')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_event_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_documents_is_indexed'))
        batch_op.drop_index(batch_op.f('ix_policy_documents_event_id'))
        batch_op.drop_index(batch_op.f('ix_policy_documents_doc_type'))

    op.drop_table('policy_documents')
    with op.batch_alter_table('itinerary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_items_event_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_items_day_date'))

    op.drop_table('itinerary_items')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_event_id'))

    op.drop_table('hotels')
    with op.batch_alter_table('gala_layouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gala_layouts_event_id'))

    op.drop_table('gala_layouts')
    op.drop_table('event_settings')
    op.drop_table('work_locations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_is_active'))

    op.drop_table('events')
    op.drop_table('departments')
    # ### end Alembic commands ###
